In [153]:
import pandas as pd
import geopandas as gpd

In [154]:
geoDF = gpd.read_file('../data/greaterAustinZipcodes.geojson')

In [155]:
geoDF.head()

,Name,number_of_records,objectid,zipcode,zipcodes_id,geometry
0,Ceasar Chavez,45,51,78702,45,"(POLYGON ((-97.69186838400699 30.248482149129,..."
1,St. Johns,30,11,78752,5,"(POLYGON ((-97.686347884619 30.332598550963, -..."
2,Onion Creek,25,32,78747,26,"(POLYGON ((-97.73618056605601 30.159870363356,..."
3,Manor,2,29,78653,23,"(POLYGON ((-97.501494615524 30.477330039287, -..."
4,River Place,2,52,78730,46,"(POLYGON ((-97.84398150237401 30.393578155125,..."

In [156]:
geotypes = geoDF.dtypes
geotypes

Name                 object
number_of_records    object
objectid             object
zipcode              object
zipcodes_id          object
geometry             object
dtype: object

In [157]:
#  import old master data

fileImport = pd.read_csv('../data/zillowCommuteData.csv')
masterDF = pd.DataFrame(fileImport)

In [158]:
masterDF.head()

,zid,address,zipcode,alat,alon,valuation,value_change,value_range_high,value_range_low,sqft,value_sqft,lot_sqft,year_built,last_sold_date,last_sold_price,commuteTime
0,70354229.0,13805 Abrahamson Court,78653,30.360686,-97.473507,139455.0,-4722.0,179897.0,108775.0,1288.0,108.27,501114.0,1980.0,NaN,NaN,40.5
1,29498621.0,8113 West Gate Boulevard,78745,30.197589,-97.828106,265041.0,-3015.0,283594.0,241187.0,940.0,281.96,12066.0,1984.0,NaN,NaN,27.7
2,144352111.0,10555 Maha Circle,78747,30.107525,-97.698309,264198.0,2091.0,290618.0,216642.0,1362.0,193.98,248410.0,1970.0,NaN,NaN,33.1
3,29440641.0,2109 Red Stone Lane,78727,30.418454,-97.696190,250406.0,-11245.0,262926.0,237886.0,1359.0,184.26,7357.0,1976.0,NaN,NaN,21.4
4,29345444.0,9 Glen Rock Drive,78738,30.341187,-97.984049,460645.0,-2983.0,483677.0,437613.0,2896.0,159.06,10802.0,1993.0,NaN,NaN,30.8

In [159]:
masterByZipCount = masterDF.groupby(by="zipcode").size()

masterByZipCountDF = pd.DataFrame({'zipcode':masterByZipCount.index, 'count':masterByZipCount.values})

masterByZipCountDF.head()

   zipcode  count
0    78610    185
1    78612     51
2    78613    171
3    78615      5
4    78616     13

In [160]:

masterByZipDF = masterDF.groupby(by="zipcode").mean()

In [161]:
masterByZipDF.head()

,zid,alat,alon,valuation,value_change,value_range_high,value_range_low,sqft,value_sqft,lot_sqft,year_built,last_sold_price,commuteTime
zipcode,,,,,,,,,,,,,
78610,6.965989e+07,30.077023,-97.784658,339900.897297,3156.237838,387880.924324,303496.886486,1988.394595,186.232432,3.996797e+05,1993.075581,119725.411765,32.495676
78612,8.280300e+07,30.158200,-97.513128,306764.156863,1656.254902,347081.470588,271572.568627,1959.019608,170.150000,3.187042e+05,1992.803922,111197.300000,34.943137
78613,7.122722e+07,30.501549,-97.828660,335957.760234,814.766082,357993.345029,315456.339181,2423.988304,141.599298,3.896852e+06,1998.421053,223097.500000,27.014620
78615,1.324773e+08,30.415515,-97.496226,409219.400000,-1312.600000,516186.600000,315034.800000,1718.000000,262.984000,1.374928e+06,1964.400000,NaN,38.420000
78616,1.015949e+08,30.062328,-97.620467,169755.307692,746.000000,201367.000000,142824.000000,1606.923077,113.600000,1.905984e+05,1991.923077,40430.000000,36.638462

In [162]:
masterByZipDF = masterByZipDF.drop(['zid','alat','alon','last_sold_price'], axis=1)
masterByZipDF.head()

,valuation,value_change,value_range_high,value_range_low,sqft,value_sqft,lot_sqft,year_built,commuteTime
zipcode,,,,,,,,,
78610,339900.897297,3156.237838,387880.924324,303496.886486,1988.394595,186.232432,3.996797e+05,1993.075581,32.495676
78612,306764.156863,1656.254902,347081.470588,271572.568627,1959.019608,170.150000,3.187042e+05,1992.803922,34.943137
78613,335957.760234,814.766082,357993.345029,315456.339181,2423.988304,141.599298,3.896852e+06,1998.421053,27.014620
78615,409219.400000,-1312.600000,516186.600000,315034.800000,1718.000000,262.984000,1.374928e+06,1964.400000,38.420000
78616,169755.307692,746.000000,201367.000000,142824.000000,1606.923077,113.600000,1.905984e+05,1991.923077,36.638462

In [163]:
masterByZipDF.reset_index(level=0, inplace=True)
masterByZipDF.head()

,zipcode,valuation,value_change,value_range_high,value_range_low,sqft,value_sqft,lot_sqft,year_built,commuteTime
0,78610,339900.897297,3156.237838,387880.924324,303496.886486,1988.394595,186.232432,3.996797e+05,1993.075581,32.495676
1,78612,306764.156863,1656.254902,347081.470588,271572.568627,1959.019608,170.150000,3.187042e+05,1992.803922,34.943137
2,78613,335957.760234,814.766082,357993.345029,315456.339181,2423.988304,141.599298,3.896852e+06,1998.421053,27.014620
3,78615,409219.400000,-1312.600000,516186.600000,315034.800000,1718.000000,262.984000,1.374928e+06,1964.400000,38.420000
4,78616,169755.307692,746.000000,201367.000000,142824.000000,1606.923077,113.600000,1.905984e+05,1991.923077,36.638462

In [164]:
masterByZipDF = pd.merge(masterByZipDF,masterByZipCountDF[['zipcode','count']],on='zipcode', how='left')
masterByZipDF.head()

,zipcode,valuation,value_change,value_range_high,value_range_low,sqft,value_sqft,lot_sqft,year_built,commuteTime,count
0,78610,339900.897297,3156.237838,387880.924324,303496.886486,1988.394595,186.232432,3.996797e+05,1993.075581,32.495676,185
1,78612,306764.156863,1656.254902,347081.470588,271572.568627,1959.019608,170.150000,3.187042e+05,1992.803922,34.943137,51
2,78613,335957.760234,814.766082,357993.345029,315456.339181,2423.988304,141.599298,3.896852e+06,1998.421053,27.014620,171
3,78615,409219.400000,-1312.600000,516186.600000,315034.800000,1718.000000,262.984000,1.374928e+06,1964.400000,38.420000,5
4,78616,169755.307692,746.000000,201367.000000,142824.000000,1606.923077,113.600000,1.905984e+05,1991.923077,36.638462,13

In [165]:
masterByZipDF.zipcode = masterByZipDF.zipcode.astype(str)
masterByZipDF.valuation = masterByZipDF.valuation.astype(int)
masterByZipDF.sqft = masterByZipDF.sqft.astype(int)
masterByZipDF.lot_sqft = masterByZipDF.lot_sqft.astype(int)
masterByZipDF.year_built = masterByZipDF.year_built.astype(int)
masterByZipDF.commuteTime = masterByZipDF.commuteTime.astype(int)
masterByZipDF.dtypes

zipcode              object
valuation             int64
value_change        float64
value_range_high    float64
value_range_low     float64
sqft                  int64
value_sqft          float64
lot_sqft              int64
year_built            int64
commuteTime           int64
count                 int64
dtype: object

In [166]:
fileImport = pd.read_csv('../data/schoolDataFINAL.csv')
schoolDF = pd.DataFrame(fileImport)

schoolDF.head()

,alat,alon,school_name,school_address,school_rating,house_zipcode
0,30.197589,-97.828106,Cowan Elementary School,"2817 Kentish Drive, Austin, TX 78748",9,78745
1,30.418454,-97.696190,Parmer Lane Elementary School,"1806 Parmer Lane, Austin, TX 78727",7,78727
2,30.341187,-97.984049,Bee Cave Elementary School,"3322 Ranch Road 620 South, Austin, TX 78738",8,78738
3,30.460441,-97.761118,Live Oak Elementary School,"8607 Anderson Mill Road, Austin, TX 78729",6,78729
4,30.374096,-97.775259,Doss Elementary School,"7005 Northledge Drive, Austin, TX 78731",9,78731

In [168]:
schoolDF.dtypes

alat              float64
alon              float64
school_name        object
school_address     object
school_rating       int64
house_zipcode       int64
dtype: object

In [169]:
schoolSinglePointDF = schoolDF.groupby(by=['alat','alon']).mean()
schoolSinglePointDF.head()

                      school_rating  house_zipcode
alat      alon
29.988799 -97.744645       3.333333        78640.0
29.993041 -97.805147       3.666667        78640.0
29.993916 -97.740712       3.333333        78640.0
29.994435 -97.817311       3.666667        78640.0
29.994905 -97.745289       3.333333        78640.0

In [170]:
len(schoolSinglePointDF)

5744

In [171]:

schoolSinglePointDF.house_zipcode = schoolSinglePointDF.house_zipcode.astype(int)
schoolSinglePointDF.head()

                      school_rating  house_zipcode
alat      alon
29.988799 -97.744645       3.333333          78640
29.993041 -97.805147       3.666667          78640
29.993916 -97.740712       3.333333          78640
29.994435 -97.817311       3.666667          78640
29.994905 -97.745289       3.333333          78640

In [172]:
schoolSinglePointDF.to_csv('schoolSinglePointData.csv', index=False, header=True)

In [137]:
schoolRatingsByZipDF = schoolSinglePointDF.groupby(by="house_zipcode").mean()

In [173]:
print(len(schoolRatingsByZipDF))
schoolRatingsByZipDF = schoolRatingsByZipDF.rename(columns={'house_zipcode':'zipcode'})
print(schoolRatingsByZipDF.head())
schoolRatingsByZipDF.to_csv('../data/schoolRatingsByZip.csv', index=False, header=True)

62
   index  zipcode  school_rating
0      0    78610       3.866366
1      1    78612       3.942593
2      2    78613       7.571279
3      3    78615       2.666667
4      4    78616       4.166667

In [174]:
schoolRatingsByZipDF.reset_index(level=0, inplace=True)
schoolRatingsByZipDF = schoolRatingsByZipDF.rename(columns={'house_zipcode':'zipcode'})
print(schoolRatingsByZipDF.dtypes)
schoolRatingsByZipDF.head()

level_0            int64
index              int64
zipcode            int64
school_rating    float64
dtype: object

   level_0  index  zipcode  school_rating
0        0      0    78610       3.866366
1        1      1    78612       3.942593
2        2      2    78613       7.571279
3        3      3    78615       2.666667
4        4      4    78616       4.166667

In [175]:
geoWithEpicProps = geoDF.merge(masterByZipDF, on='zipcode')
print(len(geoWithEpicProps))
geoWithEpicProps.head()

56

,Name,number_of_records,objectid,zipcode,zipcodes_id,geometry,valuation,value_change,value_range_high,value_range_low,sqft,value_sqft,lot_sqft,year_built,commuteTime,count
0,Ceasar Chavez,45,51,78702,45,"(POLYGON ((-97.69186838400699 30.248482149129,...",463814,-4359.918033,5.114049e+05,426519.131148,1315,391.534262,8248,1961,20,61
1,St. Johns,30,11,78752,5,"(POLYGON ((-97.686347884619 30.332598550963, -...",327760,4323.772727,3.512570e+05,304699.681818,1468,242.368636,9193,1967,25,44
2,Onion Creek,25,32,78747,26,"(POLYGON ((-97.73618056605601 30.159870363356,...",294209,311.270968,3.202592e+05,267198.722581,1928,164.934452,221262,1992,32,155
3,Manor,2,29,78653,23,"(POLYGON ((-97.501494615524 30.477330039287, -...",282614,803.293629,3.248229e+05,247473.476454,1911,156.933075,252189,1990,34,361
4,River Place,2,52,78730,46,"(POLYGON ((-97.84398150237401 30.393578155125,...",1042304,-3122.852761,1.146469e+06,951836.742331,3943,261.923681,86992,1995,25,163

In [176]:
zipsToDrop = [78620,78669,78619]
newDF = gpd.GeoDataFrame()

for index, row in geoWithEpicProps.iterrows():
    keep = True
    for zip in zipsToDrop:
        if int(row['zipcode']) == zip:
#             print(row['zipcode'] + " " + str(zip))
            keep = False
    if keep:
        newDF = newDF.append(geoWithEpicProps.iloc[index])
#         print(index)
len(newDF)

53

In [177]:
newDF.to_csv('testDeleteThisFile.csv', index=False, header=True)

In [178]:
newDF.dtypes
newDF.zipcode = newDF.zipcode.astype(int)
newDF.dtypes

Name                  object
commuteTime          float64
count                float64
geometry              object
lot_sqft             float64
number_of_records     object
objectid              object
sqft                 float64
valuation            float64
value_change         float64
value_range_high     float64
value_range_low      float64
value_sqft           float64
year_built           float64
zipcode                int64
zipcodes_id           object
dtype: object

In [179]:
newDF = pd.merge(newDF,schoolRatingsByZipDF[['zipcode','school_rating']],on='zipcode', how='left')

In [180]:
newDF.to_csv('test2DeleteThisFile.csv', index=False, header=True)
newDF

,Name,commuteTime,count,geometry,lot_sqft,number_of_records,objectid,sqft,valuation,value_change,value_range_high,value_range_low,value_sqft,year_built,zipcode,zipcodes_id,school_rating
0,Ceasar Chavez,20.0,61.0,"(POLYGON ((-97.69186838400699 30.248482149129,...",8248.0,45,51,1315.0,463814.0,-4359.918033,5.114049e+05,4.265191e+05,391.534262,1961.0,78702,45,4.606061
1,St. Johns,25.0,44.0,"(POLYGON ((-97.686347884619 30.332598550963, -...",9193.0,30,11,1468.0,327760.0,4323.772727,3.512570e+05,3.046997e+05,242.368636,1967.0,78752,5,3.567568
2,Onion Creek,32.0,155.0,"(POLYGON ((-97.73618056605601 30.159870363356,...",221262.0,25,32,1928.0,294209.0,311.270968,3.202592e+05,2.671987e+05,164.934452,1992.0,78747,26,3.864428
3,Manor,34.0,361.0,"(POLYGON ((-97.501494615524 30.477330039287, -...",252189.0,2,29,1911.0,282614.0,803.293629,3.248229e+05,2.474735e+05,156.933075,1990.0,78653,23,3.619241
4,River Place,25.0,163.0,"(POLYGON ((-97.84398150237401 30.393578155125,...",86992.0,2,52,3943.0,1042304.0,-3122.852761,1.146469e+06,9.518367e+05,261.923681,1995.0,78730,46,8.534144
5,Rosedale,19.0,30.0,"(POLYGON ((-97.727930087068 30.329060677533, -...",10367.0,4,14,1707.0,562565.0,-2683.066667,6.131776e+05,5.137386e+05,353.620667,1954.0,78756,8,5.000000
6,Daffan,29.0,86.0,"(POLYGON ((-97.560732021207 30.249033539416, -...",85483.0,34,13,1606.0,221759.0,166.488372,2.455083e+05,1.982377e+05,146.239651,1991.0,78724,7,3.000000
7,Circle C,27.0,128.0,"(POLYGON ((-97.89002339747999 30.209417172216,...",37645.0,7,3,2897.0,476522.0,-72.242188,5.090220e+05,4.469405e+05,169.314688,1995.0,78739,56,8.554131
8,Rosewood,34.0,75.0,"(POLYGON ((-97.623389203909 30.26459943964, -9...",228265.0,5,38,1495.0,234603.0,563.920000,2.649317e+05,2.072022e+05,168.077200,1988.0,78725,32,3.011364
9,Montopolis,25.0,20.0,"(POLYGON ((-97.64044061083 30.256471217292, -9...",301601.0,,42,1303.0,275782.0,3722.300000,3.068197e+05,2.451083e+05,234.380500,1977.0,78742,36,3.222222
10,Manchaca,31.0,93.0,"(POLYGON ((-97.90410646193899 30.164602161691,...",62618.0,,55,2191.0,365764.0,-67.741935,3.975469e+05,3.374777e+05,177.568280,1985.0,78652,49,5.483539
11,Buda,32.0,185.0,"(POLYGON ((-97.85678113068801 30.130439202859,...",399679.0,4,72,1988.0,339900.0,3156.237838,3.878809e+05,3.034969e+05,186.232432,1993.0,78610,62,3.866366
12,Allandale,21.0,118.0,"(POLYGON ((-97.736008616771 30.378574225961, -...",10328.0,40,59,1564.0,474066.0,-3261.915254,5.095556e+05,4.373652e+05,311.977966,1960.0,78757,53,5.815972
13,Walnut Creek,22.0,133.0,"(POLYGON ((-97.712237884006 30.348009934938, -...",10417.0,95,67,1727.0,310263.0,864.195489,3.319146e+05,2.905313e+05,190.528271,1976.0,78758,78,4.029202
14,McKinney,27.0,122.0,"(POLYGON ((-97.68336103053799 30.214328386587,...",45246.0,113,41,1466.0,240757.0,1853.991803,2.721848e+05,2.168106e+05,174.625738,1981.0,78744,35,2.556061
15,Steiner Ranch,32.0,173.0,"(POLYGON ((-97.873035696592 30.438068964232, -...",33035.0,3,5,3501.0,808190.0,-1179.791908,8.718362e+05,7.454592e+05,221.685260,2000.0,78732,58,8.709804
16,San Leanna,29.0,251.0,"(POLYGON ((-97.83150768063 30.190000732324, -9...",3057548.0,26,58,1995.0,338954.0,327.486056,3.648883e+05,3.160600e+05,179.860916,1990.0,78748,52,5.381102
17,Sunset Valley,25.0,289.0,"(POLYGON ((-97.792080707403 30.231834646931, -...",15138.0,53,57,1569.0,350775.0,296.757785,3.818897e+05,3.211941e+05,234.865502,1974.0,78745,51,4.541985
18,Downtown,18.0,5.0,"(POLYGON ((-97.735995628403 30.251018125831, -...",4654.0,,68,954.0,780296.0,6662.600000,1.029599e+06,6.150298e+05,770.200000,1968.0,78701,79,NaN
19,Oak Hill,30.0,227.0,"(POLYGON ((-97.92213310176101 30.293008752047,...",140891.0,4,47,2451.0,534124.0,3547.881057,5.877102e+05,4.871711e+05,232.194714,1987.0,78736,41,8.544715
20,Jester Estates,25.0,208.0,"(POLYGON ((-97.791060914927 30.450489963727, -...",2625262.0,3,23,2767.0,514529.0,-1238.490385,5.515013e+05,4.802377e+05,186.464519,1985.0,78750,17,8.783841
21,West Lake,22.0,447.0,"(POLYGON ((-97.776638274294 30.32301136743, -9...",58455.0,1,22,3798.0,1357526.0,-7714.919463,1.525313e+06,1.209063e+06,366.055660,1986.0,78746,16,8.592361
22,Lakeway,29.0,336.0,"(POLYGON ((-97.92087214214 30.434961552898, -9...",1956499.0,,71,3019.0,759139.0,-3242.419643,8.541161e+05,6.858043e+05,247.886310,1991.0,78734,61,7.134100
23,Mueller,24.0,132.0,"(POLYGON ((-97.66540392470699 30.28564428704, ...",12573.0,45,15,1638.0,373772.0,-2903.462121,4.028058e+05,3.443730e+05,243.300227,1967.0,78723,9,3.289855
24,Travis,24.0,129.0,"(POLYGON ((-97.697299006422 30.440042411985, -...",2717154.0,17,66,1921.0,354759.0,-322.875969,3.832766e+05,3.286233e+05,192.519535,1983.0,78727,77,5.589080
25,Pflugerville,26.0,456.0,"(POLYGON ((-97.576537392411 30.500861682886, -...",558133.0,18,80,2211.0,280526.0,-1644.853070,3.031416e+05,2.593474e+05,133.299013,1995.0,78660,70,6.344991
26,Bear Creek,28.0,241.0,"(POLYGON ((-98.01876358646901 30.241670236524,...",176508.0,1,6,2832.0,544153.0,-1933.468880,5.948750e+05,4.979073e+05,205.845892,1992.0,78737,59,8.914957
27,Lago Vista,39.0,130.0,"(POLYGON ((-97.91075592833 30.501102017302, -9...",135184.0,,4,2832.0,705579.0,3198.592308,7.982846e+05,6.289047e+05,236.486462,1991.0,78645,57,6.878205
28,Round Rock East,25.0,118.0,"(POLYGON ((-97.601231608769 30.536445248505, -...",44650.0,,69,2145.0,280289.0,2807.322034,3.015106e+05,2.590342e+05,138.295000,1992.0,78664,80,6.236667
29,Del Valle,31.0,273.0,"(POLYGON ((-97.516243132228 30.219067445444, -...",320927.0,11,18,1617.0,248513.0,5084.754579,2.938812e+05,2.092901e+05,166.073553,1986.0,78617,12,3.301282
30,Jollyville,24.0,105.0,"(POLYGON ((-97.721385934274 30.473586068595, -...",13302.0,10,8,2057.0,315833.0,-519.085714,3.370766e+05,2.946895e+05,158.917238,1988.0,78729,2,6.552632
31,Brushy Creek,27.0,104.0,"(POLYGON ((-97.707404489464 30.474830115136, -...",12351.0,2,7,2824.0,397040.0,-530.173077,4.221935e+05,3.723234e+05,142.687115,2002.0,78717,1,8.595614
32,Wells Branch,24.0,76.0,"(POLYGON ((-97.67106481390201 30.471325903972,...",9983.0,5,39,1782.0,271598.0,-1300.868421,2.876618e+05,2.546456e+05,159.037895,1990.0,78728,33,4.370833
33,Barton Creek,22.0,171.0,"(POLYGON ((-97.86242229836699 30.297009026937,...",57760.0,4,25,4100.0,1213513.0,-2144.631579,1.338311e+06,1.100966e+06,278.786199,1996.0,78735,19,8.058458
34,West Campus,16.0,29.0,"(POLYGON ((-97.729785804383 30.298712425534, -...",8748.0,1,64,1962.0,701809.0,-3498.793103,7.922187e+05,6.194403e+05,389.416552,1943.0,78705,75,3.833333
35,Legend Oaks,25.0,181.0,"(POLYGON ((-97.823317812363 30.234865343083, -...",14666.0,20,45,2219.0,401392.0,1768.182320,4.257744e+05,3.775364e+05,187.228287,1989.0,78749,39,7.630081
36,Bee Cave,31.0,288.0,"(POLYGON ((-98.006227061769 30.360796441505, -...",1529725.0,3,36,3860.0,850849.0,-2307.635417,9.436205e+05,7.714201e+05,216.045417,1999.0,78738,30,8.602941
37,Pleasant Valley,23.0,51.0,"(POLYGON ((-97.706532971703 30.250246876232, -...",14075.0,56,40,1485.0,333628.0,-3848.764706,3.730583e+05,3.016399e+05,241.683529,1982.0,78741,34,2.777778
38,Bergstrom,27.0,96.0,"(POLYGON ((-97.65158473005 30.2014335432, -97....",271512.0,,46,1756.0,267093.0,5565.406250,3.113667e+05,2.286281e+05,171.870521,1983.0,78719,40,3.428571
39,Great Hills,22.0,210.0,"(POLYGON ((-97.747447954788 30.421623443357, -...",659623.0,11,65,2443.0,500777.0,-2321.309524,5.360749e+05,4.668886e+05,209.784429,1982.0,78759,76,8.039724
40,Four Points,29.0,96.0,"(POLYGON ((-97.82580971813699 30.455455648161,...",44410.0,7,79,3179.0,564063.0,1436.562500,6.118086e+05,5.202674e+05,181.673542,1995.0,78726,69,8.265152
41,MLK,22.0,60.0,"(POLYGON ((-97.66540392470699 30.28564428704, ...",10989.0,30,50,1298.0,333362.0,-4684.033333,3.659980e+05,3.025960e+05,277.758833,1969.0,78721,44,3.444444
42,Round Rock West,27.0,124.0,"(POLYGON ((-97.73178423090501 30.587692687517,...",25635.0,3,53,2496.0,343221.0,2785.024194,3.647917e+05,3.214328e+05,140.018065,1994.0,78681,47,8.618659
43,Hyde Park,18.0,47.0,"(POLYGON ((-97.706773570854 30.322110626205, -...",7743.0,11,34,1445.0,498828.0,2769.723404,5.374738e+05,4.607460e+05,367.610000,1950.0,78751,28,3.753333
44,Nortwest Hills,19.0,194.0,"(POLYGON ((-97.745986647983 30.361382677137, -...",2448963.0,14,54,3042.0,959133.0,-5113.056701,1.071641e+06,8.680509e+05,303.139588,1979.0,78731,48,7.913934
45,Austin Lake Hills,25.0,204.0,"(POLYGON ((-97.84295675908101 30.323103857241,...",10622178.0,,20,3845.0,1089680.0,-10513.044118,1.213867e+06,9.789442e+05,291.942304,1993.0,78733,14,9.394231
46,Leander,33.0,174.0,"(POLYGON ((-97.85060986438801 30.626802822383,...",176577.0,7,30,2693.0,558860.0,-2088.172414,6.188582e+05,5.000245e+05,217.586322,1990.0,78641,24,7.211268
47,Tarrytown,18.0,132.0,"(POLYGON ((-97.766064047399 30.312959350782, -...",4350769.0,6,44,2959.0,1316262.0,2119.772727,1.501522e+06,1.174671e+06,440.290606,1959.0,78703,38,6.758503
48,Cherrywood,18.0,48.0,"(POLYGON ((-97.70395298822901 30.282576738999,...",8323.0,4,49,1547.0,461539.0,-2022.916667,4.958051e+05,4.289704e+05,316.757083,1958.0,78722,43,NaN
49,Bouldin Creek,20.0,178.0,"(POLYGON ((-97.754480791497 30.265071724819, -...",9991.0,54,10,1762.0,664713.0,-2243.528090,7.311508e+05,6.079558e+05,408.954551,1961.0,78704,4,5.571651
50,Harris Branch,25.0,81.0,"(POLYGON ((-97.636584255651 30.402663023969, -...",2625967.0,7,1,2044.0,258015.0,-349.950617,2.737473e+05,2.423897e+05,132.248889,1999.0,78754,54,5.080000
51,North Lamar,25.0,145.0,"(POLYGON ((-97.67151491299801 30.424380336538,...",3288437.0,81,76,1713.0,267672.0,78.641379,2.859950e+05,2.492745e+05,165.150966,1977.0,78753,66,4.079545
52,Cedar Park,27.0,171.0,"(POLYGON ((-97.838280724409 30.539888366136, -...",3896851.0,8,19,2423.0,335957.0,814.766082,3.579933e+05,3.154563e+05,141.599298,1998.0,78613,13,7.571279

In [181]:
newDF['school_rating'].fillna(0, inplace=True)
newDF.head()

,Name,commuteTime,count,geometry,lot_sqft,number_of_records,objectid,sqft,valuation,value_change,value_range_high,value_range_low,value_sqft,year_built,zipcode,zipcodes_id,school_rating
0,Ceasar Chavez,20.0,61.0,"(POLYGON ((-97.69186838400699 30.248482149129,...",8248.0,45,51,1315.0,463814.0,-4359.918033,5.114049e+05,426519.131148,391.534262,1961.0,78702,45,4.606061
1,St. Johns,25.0,44.0,"(POLYGON ((-97.686347884619 30.332598550963, -...",9193.0,30,11,1468.0,327760.0,4323.772727,3.512570e+05,304699.681818,242.368636,1967.0,78752,5,3.567568
2,Onion Creek,32.0,155.0,"(POLYGON ((-97.73618056605601 30.159870363356,...",221262.0,25,32,1928.0,294209.0,311.270968,3.202592e+05,267198.722581,164.934452,1992.0,78747,26,3.864428
3,Manor,34.0,361.0,"(POLYGON ((-97.501494615524 30.477330039287, -...",252189.0,2,29,1911.0,282614.0,803.293629,3.248229e+05,247473.476454,156.933075,1990.0,78653,23,3.619241
4,River Place,25.0,163.0,"(POLYGON ((-97.84398150237401 30.393578155125,...",86992.0,2,52,3943.0,1042304.0,-3122.852761,1.146469e+06,951836.742331,261.923681,1995.0,78730,46,8.534144

In [182]:
fileImport = pd.read_csv('../data/crimeData.csv')
crimeDF = pd.DataFrame(fileImport)

In [183]:
crimeDF

,GO Primary Key,Council District,offenseDetails,offenseCategory,GO Report Date,GO Location,Clearance Status,Clearance Date,GO District,zipcode,GO Census Tract,clat,clon,Severity
0,2.016102e+08,8.0,AGG ASLT ENHANC STRANGL/SUFFOC,Agg Assault,01-Jan-16,8600 W SH 71,C,12-Jan-16,D,78735,19.08,30.67322,100.62796,4
1,2.016106e+08,9.0,THEFT,Theft,01-Jan-16,219 E 6TH ST,C,04-Jan-16,G,78701,11.00,31.14957,100.70462,1
2,2.016109e+08,4.0,AGG ROBBERY/DEADLY WEAPON,Robbery,01-Jan-16,701 W LONGSPUR BLVD,N,03-May-16,E,78753,18.23,31.29181,101.06923,5
3,2.016109e+08,9.0,THEFT,Theft,01-Jan-16,404 COLORADO ST,N,22-Jan-16,G,78701,11.00,31.13643,100.70357,1
4,2.016111e+08,1.0,DEADLY CONDUCT,Agg Assault,01-Jan-16,8002 TAPO LN,N,08-Jan-16,C,78724,22.08,31.46947,100.77985,4
5,2.016112e+08,3.0,ROBBERY BY ASSAULT,Robbery,01-Jan-16,1601 ROYAL CREST DR,N,01-Nov-16,H,78741,23.16,31.18667,100.60221,5
6,2.016112e+08,3.0,AGG ASSAULT FAM/DATE VIOLENCE,Agg Assault,01-Jan-16,1600 WICKERSHAM LN,C,01-Jan-16,H,78741,23.18,31.22230,100.59265,4
7,2.016112e+08,5.0,AGG ASLT STRANGLE/SUFFOCATE,Agg Assault,01-Jan-16,4009 VICTORY DR,C,03-Feb-16,D,78704,20.04,30.99793,100.58337,4
8,2.016112e+08,5.0,BURGLARY NON RESIDENCE,Burglary,01-Jan-16,811 W SLAUGHTER LN,N,04-Feb-16,F,78748,24.21,30.95553,100.35959,2
9,2.016113e+08,4.0,BURGLARY OF RESIDENCE,Burglary,01-Jan-16,8930 GALEWOOD DR,C,12-Feb-16,E,78758,18.20,31.21931,101.06738,2
10,2.016113e+08,4.0,AUTO THEFT,Auto Theft,01-Jan-16,9619 POINT VISTA PL,N,01-Jan-16,E,78753,18.33,31.33869,101.03524,3
11,2.016113e+08,2.0,AUTO THEFT,Auto Theft,01-Jan-16,4323 S IH 35 SVRD NB,N,01-Jan-16,F,78744,24.11,31.11632,100.50167,3
12,2.016113e+08,2.0,DEADLY CONDUCT,Agg Assault,01-Jan-16,5804 NEEDLE NOOK CT,N,04-Jan-16,F,78744,24.31,31.15830,100.42476,4
13,2.016113e+08,5.0,BURGLARY OF RESIDENCE,Burglary,01-Jan-16,10800 RIVER PLANTATION DR,N,05-Jan-16,F,78747,24.28,31.02916,100.23485,2
14,2.016113e+08,5.0,BURGLARY OF RESIDENCE,Burglary,01-Jan-16,9409 BERNOULLI DR,N,05-Jan-16,F,78748,17.46,30.85304,100.39671,2
15,2.016113e+08,9.0,AGG ASLT STRANGLE/SUFFOCATE,Agg Assault,01-Jan-16,1100 E OLTORF ST,N,06-Jan-16,H,78704,23.08,31.13907,100.59041,4
16,2.016114e+08,7.0,AGG ASSAULT FAM/DATE VIOLENCE,Agg Assault,01-Jan-16,5515 WOODROW AVE,N,20-Jan-16,I,78756,2.05,31.16795,100.92335,4
17,2.016114e+08,6.0,BURGLARY OF RESIDENCE,Burglary,01-Jan-16,4400 ANDALUSIA DR,C,20-Apr-16,A,78759,17.54,31.14668,101.21066,2
18,2.016114e+08,9.0,BURGLARY OF RESIDENCE,Burglary,01-Jan-16,2338 WILSON ST,N,05-Jan-16,D,78704,13.05,31.10158,100.60953,2
19,2.016114e+08,9.0,BURGLARY OF RESIDENCE,Burglary,01-Jan-16,2041 ZACH SCOTT ST,N,05-Jan-16,B,78723,3.06,31.26322,100.80484,2
20,2.016114e+08,9.0,BURGLARY NON RESIDENCE,Burglary,01-Jan-16,323 E 6TH ST,N,21-Jan-16,G,78701,11.00,31.15326,100.70387,2
21,2.016114e+08,5.0,BURGLARY OF RESIDENCE,Burglary,01-Jan-16,1119 ECHO LN,N,05-Jan-16,F,78745,24.24,30.97863,100.45181,2
22,2.016115e+08,5.0,BURGLARY NON RESIDENCE,Burglary,01-Jan-16,10140 OLD SAN ANTONIO RD,N,05-Feb-16,F,78748,24.07,30.98369,100.28961,2
23,2.016115e+08,3.0,BURGLARY NON RESIDENCE,Burglary,01-Jan-16,903 MONTOPOLIS DR,N,01-Mar-16,H,78741,23.12,31.29173,100.59178,2
24,2.016116e+08,8.0,BURGLARY NON RESIDENCE,Burglary,01-Jan-16,5100 ROADRUNNER LN,N,05-Feb-16,D,78749,17.49,30.86212,100.58406,2
25,2.016116e+08,9.0,BURGLARY OF VEHICLE,Theft,01-Jan-16,119 E 10TH ST,N,14-Jan-16,G,78701,11.00,31.15057,100.71995,3
26,2.016116e+08,7.0,THEFT BY SHOPLIFTING,Theft,01-Jan-16,3311 ESPERANZA XING,N,14-Jan-16,A,78758,18.49,31.18197,101.18869,1
27,2.016117e+08,2.0,BURGLARY OF VEHICLE,Theft,01-Jan-16,4749 E BEN WHITE BLVD SVRD EB,N,02-Jan-16,F,78744,24.31,31.18931,100.51193,3
28,2.016117e+08,5.0,THEFT,Theft,01-Jan-16,9300 S IH 35 SVRD SB,C,16-Feb-16,F,78748,24.21,31.00423,100.33116,1
29,2.016117e+08,2.0,AUTO THEFT,Auto Theft,01-Jan-16,5200 BERYL OAK DR,C,02-Jan-16,F,78744,24.31,31.16496,100.43740,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36549,2.016366e+10,4.0,AUTO THEFT,Auto Theft,31-Dec-16,1220 CAMINO LA COSTA,N,05-Jan-17,I,78752,18.12,31.29001,100.91827,3
36550,2.016366e+10,1.0,AGG ROBBERY/DEADLY WEAPON,Robbery,31-Dec-16,7801 FM 969 RD,C,19-Jan-17,C,78725,22.08,31.44951,100.75727,5
36551,2.016505e+10,2.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,12820 QUIRIN DR,N,02-Jan-17,H,78617,24.33,31.54685,100.37363,3
36552,2.016505e+10,1.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,12041 DESSAU RD,N,02-Jan-17,E,78754,18.34,31.41933,101.12339,3
36553,2.016505e+10,3.0,THEFT,Theft,31-Dec-16,2707 S IH 35 SVRD NB,NaN,NaN,H,78741,23.07,31.14497,100.56575,1
36554,2.016505e+10,9.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,2701 RIO GRANDE ST,N,03-Jan-17,B,78705,6.03,31.13680,100.79726,3
36555,2.016505e+10,8.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,6636 W WILLIAM CANNON DR,N,11-Jan-17,D,78735,19.15,30.76772,100.61056,3
36556,2.016505e+10,5.0,THEFT,Theft,31-Dec-16,4211 S LAMAR BLVD NB,N,04-Jan-17,D,78704,20.04,30.98880,100.58093,1
36557,2.016505e+10,5.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,5705 WEST GATE BLVD,N,04-Jan-17,D,78745,17.13,30.94374,100.52233,3
36558,2.016505e+10,7.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,5400 N LAMAR BLVD,N,03-Jan-17,I,78756,2.05,31.18092,100.90506,3
36559,2.016505e+10,3.0,THEFT OF BICYCLE,Theft,31-Dec-16,2716 E 3RD ST,N,22-Feb-17,C,78702,9.02,31.24129,100.66233,1
36560,2.016505e+10,3.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,2201 MONTOPOLIS DR,N,02-Jan-17,H,78741,23.12,31.26801,100.54469,3
36561,2.016505e+10,9.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,3909 N IH 35 SVRD NB,N,02-Jan-17,C,78722,3.07,31.22010,100.81176,3
36562,2.016505e+10,9.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,1620 E RIVERSIDE DR,NaN,NaN,H,78741,23.04,31.18446,100.62525,3
36563,2.016505e+10,7.0,THEFT,Theft,31-Dec-16,9061 RESEARCH BLVD NB,N,02-Jan-17,A,78758,18.49,31.18443,101.09473,1
36564,2.016505e+10,1.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,12041 DESSAU RD,N,02-Jan-17,E,78754,18.34,31.41933,101.12339,3
36565,2.016505e+10,4.0,THEFT,Theft,31-Dec-16,8601 RESEARCH BLVD SVRD NB,N,02-Jan-17,E,78758,18.05,31.21691,101.05147,1
36566,2.016505e+10,2.0,THEFT,Theft,31-Dec-16,6607 S IH 35 SVRD NB,N,04-Jan-17,F,78744,24.27,31.06736,100.41724,1
36567,2.016505e+10,8.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,4970 W US 290 HWY WB,N,04-Jan-17,D,78735,19.15,30.90597,100.57931,3
36568,2.016505e+10,7.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,2211 W NORTH LOOP BLVD,N,04-Jan-17,B,78756,2.06,31.14330,100.91389,3
36569,2.016505e+10,8.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,5604 SOUTHWEST PKWY,N,11-Jan-17,D,78735,19.14,30.82154,100.62686,3
36570,2.016505e+10,8.0,THEFT,Theft,31-Dec-16,5106 MAULDING PASS,N,04-Jan-17,D,78749,17.49,30.81732,100.55829,1
36571,2.016505e+10,3.0,THEFT,Theft,31-Dec-16,2200 S PLEASANT VALLEY RD,N,22-Feb-17,H,78741,23.16,31.19912,100.57599,1
36572,2.016505e+10,2.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,901 LITTLE TEXAS LN,N,04-Jan-17,F,78745,24.02,31.06553,100.45028,3
36573,2.016505e+10,4.0,THEFT,Theft,31-Dec-16,7500 BLESSING AVE,N,16-Feb-17,I,78752,18.12,31.29407,100.94386,1
36574,2.016505e+10,7.0,THEFT,Theft,31-Dec-16,8822 MC CANN DR,N,03-Jan-17,B,78757,18.17,31.17454,101.09065,1
36575,2.016505e+10,9.0,THEFT,Theft,31-Dec-16,123 W 6TH ST,N,03-Jan-17,G,78701,11.00,31.13924,100.70794,1
36576,2.016801e+10,1.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,5601 EXETER DR,N,16-Jan-17,I,78723,21.06,31.32812,100.84356,3
36577,2.016801e+10,3.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,101 HERGOTZ LN,N,12-Jan-17,H,78742,23.10,31.31778,100.62481,3
36578,2.016801e+10,9.0,BURGLARY OF VEHICLE,Theft,31-Dec-16,701 W 28TH ST,N,16-Jan-17,B,78705,6.03,31.13521,100.79906,3

In [184]:
crimeRatingsByZipDF = crimeDF.groupby(by="zipcode").sum()
crimeRatingsByZipDF

,GO Primary Key,Council District,GO Census Tract,clat,clon,Severity
zipcode,,,,,,
78613,5.882525e+12,2028.0,68675.59,10453.50081,34287.72964,454
78617,4.904280e+12,546.0,35876.19,8627.67090,27515.21697,596
78652,3.026746e+11,80.0,385.12,495.22043,1603.73795,40
78653,7.628128e+11,40.0,896.18,1514.68294,4851.45442,90
78660,3.147624e+12,1096.0,3227.84,5493.78695,17729.80286,325
78664,4.033009e+10,0.0,430.13,62.75664,203.24861,5
78701,3.745052e+13,17383.0,21518.06,63077.68127,203932.41475,3424
78702,2.739265e+13,3533.0,14144.79,48670.20506,156985.76495,3406
78703,1.178689e+13,6100.0,8982.72,20393.96182,66091.21189,1202
78704,4.506745e+13,14321.0,42160.94,78172.81523,253027.80526,4923
78705,2.045260e+13,10031.0,5884.24,34632.18609,112079.99793,2101
78712,8.268519e+10,29.0,26.05,155.83977,503.89124,9
78717,5.466955e+12,1806.0,61318.13,9328.38691,30547.14380,500
78719,2.799037e+12,330.0,1617000.00,5178.68151,16578.80932,238
78721,8.599379e+12,847.0,10558.31,15692.69191,50464.90029,1153
78722,4.725138e+12,1794.0,945.48,8056.68910,26003.82358,528
78723,3.730270e+13,6764.0,34514.56,62608.02754,201715.63887,3988
78724,9.203760e+12,525.0,11641.94,16605.68061,53235.83460,1251
78725,1.322750e+12,143.0,1532.88,2229.39754,7150.93538,165
78726,3.974644e+12,1302.0,3737.74,6687.32046,21974.75464,467
78727,9.301107e+12,3480.0,10834.24,16355.21089,53076.83567,993
78728,1.230016e+11,28.0,130.34,219.13511,709.33257,19
78729,9.859787e+12,3288.0,109243.01,17026.98609,55652.08107,1139
78730,8.549764e+11,420.0,810.02,1419.84923,4648.71577,92
78731,9.381446e+12,5004.0,6140.84,15754.36234,51201.50865,1087
78732,2.016504e+10,6.0,17.65,30.77864,101.19246,1
78735,5.032269e+12,2213.0,5657.78,9113.50474,29781.23166,606
78736,2.026547e+12,912.0,2016.66,3497.05034,11468.38601,252
78737,2.016504e+10,8.0,17.33,30.68105,100.54936,1
78739,2.615753e+12,1176.0,2601.68,4508.84271,14758.41255,344
78741,5.666882e+13,10906.0,75041.58,102433.93158,330104.67266,7095
78742,1.076777e+12,154.0,1316.72,1786.57717,5733.69197,116
78744,3.412144e+13,4159.0,46694.90,60013.80634,193626.60319,4164
78745,3.856901e+13,7624.0,47146.96,68318.79958,221372.98975,4576
78746,1.518548e+13,6474.0,15748.52,25516.87388,82983.67260,1396
78747,3.987066e+12,672.0,5459.95,6996.47778,22562.08236,519
78748,2.302342e+13,6363.0,29454.80,41677.85593,135156.46570,2517
78749,1.446905e+13,6248.0,13666.96,24066.74271,78507.82851,1373
78750,6.142259e+12,2250.0,41188.96,10186.92114,33328.05804,684
78751,1.594305e+13,7060.0,5920.61,28085.74955,90772.50897,1683
78752,2.194510e+13,4605.0,21909.63,39305.35170,126880.12174,2957
78753,5.160660e+13,13847.0,56212.90,96568.56974,311633.10708,6203
78754,6.961172e+12,427.0,7408.08,12658.89242,40714.47404,837
78756,5.941500e+12,2447.0,675.47,10062.58899,32593.47672,604
78757,1.879625e+13,7448.0,17522.85,33174.79149,107484.77359,2098
78758,4.176701e+13,12871.0,44433.73,75944.10120,245825.01418,5189
78759,2.120335e+13,9858.0,23808.13,36844.70978,119805.12668,2260

In [185]:

crimeRatingsByZipDF.reset_index(level=0, inplace=True)
crimeRatingsByZipDF.dtypes
# newDF.zipcode = newDF.zipcode.astype(int)
# newDF.dtypes

zipcode               int64
GO Primary Key      float64
Council District    float64
GO Census Tract     float64
clat                float64
clon                float64
Severity              int64
dtype: object

In [186]:
newDF = pd.merge(newDF,crimeRatingsByZipDF[['zipcode','Severity']],on='zipcode', how='left')

In [187]:
newDF

,Name,commuteTime,count,geometry,lot_sqft,number_of_records,objectid,sqft,valuation,value_change,value_range_high,value_range_low,value_sqft,year_built,zipcode,zipcodes_id,school_rating,Severity
0,Ceasar Chavez,20.0,61.0,"(POLYGON ((-97.69186838400699 30.248482149129,...",8248.0,45,51,1315.0,463814.0,-4359.918033,5.114049e+05,4.265191e+05,391.534262,1961.0,78702,45,4.606061,3406.0
1,St. Johns,25.0,44.0,"(POLYGON ((-97.686347884619 30.332598550963, -...",9193.0,30,11,1468.0,327760.0,4323.772727,3.512570e+05,3.046997e+05,242.368636,1967.0,78752,5,3.567568,2957.0
2,Onion Creek,32.0,155.0,"(POLYGON ((-97.73618056605601 30.159870363356,...",221262.0,25,32,1928.0,294209.0,311.270968,3.202592e+05,2.671987e+05,164.934452,1992.0,78747,26,3.864428,519.0
3,Manor,34.0,361.0,"(POLYGON ((-97.501494615524 30.477330039287, -...",252189.0,2,29,1911.0,282614.0,803.293629,3.248229e+05,2.474735e+05,156.933075,1990.0,78653,23,3.619241,90.0
4,River Place,25.0,163.0,"(POLYGON ((-97.84398150237401 30.393578155125,...",86992.0,2,52,3943.0,1042304.0,-3122.852761,1.146469e+06,9.518367e+05,261.923681,1995.0,78730,46,8.534144,92.0
5,Rosedale,19.0,30.0,"(POLYGON ((-97.727930087068 30.329060677533, -...",10367.0,4,14,1707.0,562565.0,-2683.066667,6.131776e+05,5.137386e+05,353.620667,1954.0,78756,8,5.000000,604.0
6,Daffan,29.0,86.0,"(POLYGON ((-97.560732021207 30.249033539416, -...",85483.0,34,13,1606.0,221759.0,166.488372,2.455083e+05,1.982377e+05,146.239651,1991.0,78724,7,3.000000,1251.0
7,Circle C,27.0,128.0,"(POLYGON ((-97.89002339747999 30.209417172216,...",37645.0,7,3,2897.0,476522.0,-72.242188,5.090220e+05,4.469405e+05,169.314688,1995.0,78739,56,8.554131,344.0
8,Rosewood,34.0,75.0,"(POLYGON ((-97.623389203909 30.26459943964, -9...",228265.0,5,38,1495.0,234603.0,563.920000,2.649317e+05,2.072022e+05,168.077200,1988.0,78725,32,3.011364,165.0
9,Montopolis,25.0,20.0,"(POLYGON ((-97.64044061083 30.256471217292, -9...",301601.0,,42,1303.0,275782.0,3722.300000,3.068197e+05,2.451083e+05,234.380500,1977.0,78742,36,3.222222,116.0
10,Manchaca,31.0,93.0,"(POLYGON ((-97.90410646193899 30.164602161691,...",62618.0,,55,2191.0,365764.0,-67.741935,3.975469e+05,3.374777e+05,177.568280,1985.0,78652,49,5.483539,40.0
11,Buda,32.0,185.0,"(POLYGON ((-97.85678113068801 30.130439202859,...",399679.0,4,72,1988.0,339900.0,3156.237838,3.878809e+05,3.034969e+05,186.232432,1993.0,78610,62,3.866366,NaN
12,Allandale,21.0,118.0,"(POLYGON ((-97.736008616771 30.378574225961, -...",10328.0,40,59,1564.0,474066.0,-3261.915254,5.095556e+05,4.373652e+05,311.977966,1960.0,78757,53,5.815972,2098.0
13,Walnut Creek,22.0,133.0,"(POLYGON ((-97.712237884006 30.348009934938, -...",10417.0,95,67,1727.0,310263.0,864.195489,3.319146e+05,2.905313e+05,190.528271,1976.0,78758,78,4.029202,5189.0
14,McKinney,27.0,122.0,"(POLYGON ((-97.68336103053799 30.214328386587,...",45246.0,113,41,1466.0,240757.0,1853.991803,2.721848e+05,2.168106e+05,174.625738,1981.0,78744,35,2.556061,4164.0
15,Steiner Ranch,32.0,173.0,"(POLYGON ((-97.873035696592 30.438068964232, -...",33035.0,3,5,3501.0,808190.0,-1179.791908,8.718362e+05,7.454592e+05,221.685260,2000.0,78732,58,8.709804,1.0
16,San Leanna,29.0,251.0,"(POLYGON ((-97.83150768063 30.190000732324, -9...",3057548.0,26,58,1995.0,338954.0,327.486056,3.648883e+05,3.160600e+05,179.860916,1990.0,78748,52,5.381102,2517.0
17,Sunset Valley,25.0,289.0,"(POLYGON ((-97.792080707403 30.231834646931, -...",15138.0,53,57,1569.0,350775.0,296.757785,3.818897e+05,3.211941e+05,234.865502,1974.0,78745,51,4.541985,4576.0
18,Downtown,18.0,5.0,"(POLYGON ((-97.735995628403 30.251018125831, -...",4654.0,,68,954.0,780296.0,6662.600000,1.029599e+06,6.150298e+05,770.200000,1968.0,78701,79,0.000000,3424.0
19,Oak Hill,30.0,227.0,"(POLYGON ((-97.92213310176101 30.293008752047,...",140891.0,4,47,2451.0,534124.0,3547.881057,5.877102e+05,4.871711e+05,232.194714,1987.0,78736,41,8.544715,252.0
20,Jester Estates,25.0,208.0,"(POLYGON ((-97.791060914927 30.450489963727, -...",2625262.0,3,23,2767.0,514529.0,-1238.490385,5.515013e+05,4.802377e+05,186.464519,1985.0,78750,17,8.783841,684.0
21,West Lake,22.0,447.0,"(POLYGON ((-97.776638274294 30.32301136743, -9...",58455.0,1,22,3798.0,1357526.0,-7714.919463,1.525313e+06,1.209063e+06,366.055660,1986.0,78746,16,8.592361,1396.0
22,Lakeway,29.0,336.0,"(POLYGON ((-97.92087214214 30.434961552898, -9...",1956499.0,,71,3019.0,759139.0,-3242.419643,8.541161e+05,6.858043e+05,247.886310,1991.0,78734,61,7.134100,NaN
23,Mueller,24.0,132.0,"(POLYGON ((-97.66540392470699 30.28564428704, ...",12573.0,45,15,1638.0,373772.0,-2903.462121,4.028058e+05,3.443730e+05,243.300227,1967.0,78723,9,3.289855,3988.0
24,Travis,24.0,129.0,"(POLYGON ((-97.697299006422 30.440042411985, -...",2717154.0,17,66,1921.0,354759.0,-322.875969,3.832766e+05,3.286233e+05,192.519535,1983.0,78727,77,5.589080,993.0
25,Pflugerville,26.0,456.0,"(POLYGON ((-97.576537392411 30.500861682886, -...",558133.0,18,80,2211.0,280526.0,-1644.853070,3.031416e+05,2.593474e+05,133.299013,1995.0,78660,70,6.344991,325.0
26,Bear Creek,28.0,241.0,"(POLYGON ((-98.01876358646901 30.241670236524,...",176508.0,1,6,2832.0,544153.0,-1933.468880,5.948750e+05,4.979073e+05,205.845892,1992.0,78737,59,8.914957,1.0
27,Lago Vista,39.0,130.0,"(POLYGON ((-97.91075592833 30.501102017302, -9...",135184.0,,4,2832.0,705579.0,3198.592308,7.982846e+05,6.289047e+05,236.486462,1991.0,78645,57,6.878205,NaN
28,Round Rock East,25.0,118.0,"(POLYGON ((-97.601231608769 30.536445248505, -...",44650.0,,69,2145.0,280289.0,2807.322034,3.015106e+05,2.590342e+05,138.295000,1992.0,78664,80,6.236667,5.0
29,Del Valle,31.0,273.0,"(POLYGON ((-97.516243132228 30.219067445444, -...",320927.0,11,18,1617.0,248513.0,5084.754579,2.938812e+05,2.092901e+05,166.073553,1986.0,78617,12,3.301282,596.0
30,Jollyville,24.0,105.0,"(POLYGON ((-97.721385934274 30.473586068595, -...",13302.0,10,8,2057.0,315833.0,-519.085714,3.370766e+05,2.946895e+05,158.917238,1988.0,78729,2,6.552632,1139.0
31,Brushy Creek,27.0,104.0,"(POLYGON ((-97.707404489464 30.474830115136, -...",12351.0,2,7,2824.0,397040.0,-530.173077,4.221935e+05,3.723234e+05,142.687115,2002.0,78717,1,8.595614,500.0
32,Wells Branch,24.0,76.0,"(POLYGON ((-97.67106481390201 30.471325903972,...",9983.0,5,39,1782.0,271598.0,-1300.868421,2.876618e+05,2.546456e+05,159.037895,1990.0,78728,33,4.370833,19.0
33,Barton Creek,22.0,171.0,"(POLYGON ((-97.86242229836699 30.297009026937,...",57760.0,4,25,4100.0,1213513.0,-2144.631579,1.338311e+06,1.100966e+06,278.786199,1996.0,78735,19,8.058458,606.0
34,West Campus,16.0,29.0,"(POLYGON ((-97.729785804383 30.298712425534, -...",8748.0,1,64,1962.0,701809.0,-3498.793103,7.922187e+05,6.194403e+05,389.416552,1943.0,78705,75,3.833333,2101.0
35,Legend Oaks,25.0,181.0,"(POLYGON ((-97.823317812363 30.234865343083, -...",14666.0,20,45,2219.0,401392.0,1768.182320,4.257744e+05,3.775364e+05,187.228287,1989.0,78749,39,7.630081,1373.0
36,Bee Cave,31.0,288.0,"(POLYGON ((-98.006227061769 30.360796441505, -...",1529725.0,3,36,3860.0,850849.0,-2307.635417,9.436205e+05,7.714201e+05,216.045417,1999.0,78738,30,8.602941,NaN
37,Pleasant Valley,23.0,51.0,"(POLYGON ((-97.706532971703 30.250246876232, -...",14075.0,56,40,1485.0,333628.0,-3848.764706,3.730583e+05,3.016399e+05,241.683529,1982.0,78741,34,2.777778,7095.0
38,Bergstrom,27.0,96.0,"(POLYGON ((-97.65158473005 30.2014335432, -97....",271512.0,,46,1756.0,267093.0,5565.406250,3.113667e+05,2.286281e+05,171.870521,1983.0,78719,40,3.428571,238.0
39,Great Hills,22.0,210.0,"(POLYGON ((-97.747447954788 30.421623443357, -...",659623.0,11,65,2443.0,500777.0,-2321.309524,5.360749e+05,4.668886e+05,209.784429,1982.0,78759,76,8.039724,2260.0
40,Four Points,29.0,96.0,"(POLYGON ((-97.82580971813699 30.455455648161,...",44410.0,7,79,3179.0,564063.0,1436.562500,6.118086e+05,5.202674e+05,181.673542,1995.0,78726,69,8.265152,467.0
41,MLK,22.0,60.0,"(POLYGON ((-97.66540392470699 30.28564428704, ...",10989.0,30,50,1298.0,333362.0,-4684.033333,3.659980e+05,3.025960e+05,277.758833,1969.0,78721,44,3.444444,1153.0
42,Round Rock West,27.0,124.0,"(POLYGON ((-97.73178423090501 30.587692687517,...",25635.0,3,53,2496.0,343221.0,2785.024194,3.647917e+05,3.214328e+05,140.018065,1994.0,78681,47,8.618659,NaN
43,Hyde Park,18.0,47.0,"(POLYGON ((-97.706773570854 30.322110626205, -...",7743.0,11,34,1445.0,498828.0,2769.723404,5.374738e+05,4.607460e+05,367.610000,1950.0,78751,28,3.753333,1683.0
44,Nortwest Hills,19.0,194.0,"(POLYGON ((-97.745986647983 30.361382677137, -...",2448963.0,14,54,3042.0,959133.0,-5113.056701,1.071641e+06,8.680509e+05,303.139588,1979.0,78731,48,7.913934,1087.0
45,Austin Lake Hills,25.0,204.0,"(POLYGON ((-97.84295675908101 30.323103857241,...",10622178.0,,20,3845.0,1089680.0,-10513.044118,1.213867e+06,9.789442e+05,291.942304,1993.0,78733,14,9.394231,NaN
46,Leander,33.0,174.0,"(POLYGON ((-97.85060986438801 30.626802822383,...",176577.0,7,30,2693.0,558860.0,-2088.172414,6.188582e+05,5.000245e+05,217.586322,1990.0,78641,24,7.211268,NaN
47,Tarrytown,18.0,132.0,"(POLYGON ((-97.766064047399 30.312959350782, -...",4350769.0,6,44,2959.0,1316262.0,2119.772727,1.501522e+06,1.174671e+06,440.290606,1959.0,78703,38,6.758503,1202.0
48,Cherrywood,18.0,48.0,"(POLYGON ((-97.70395298822901 30.282576738999,...",8323.0,4,49,1547.0,461539.0,-2022.916667,4.958051e+05,4.289704e+05,316.757083,1958.0,78722,43,0.000000,528.0
49,Bouldin Creek,20.0,178.0,"(POLYGON ((-97.754480791497 30.265071724819, -...",9991.0,54,10,1762.0,664713.0,-2243.528090,7.311508e+05,6.079558e+05,408.954551,1961.0,78704,4,5.571651,4923.0
50,Harris Branch,25.0,81.0,"(POLYGON ((-97.636584255651 30.402663023969, -...",2625967.0,7,1,2044.0,258015.0,-349.950617,2.737473e+05,2.423897e+05,132.248889,1999.0,78754,54,5.080000,837.0
51,North Lamar,25.0,145.0,"(POLYGON ((-97.67151491299801 30.424380336538,...",3288437.0,81,76,1713.0,267672.0,78.641379,2.859950e+05,2.492745e+05,165.150966,1977.0,78753,66,4.079545,6203.0
52,Cedar Park,27.0,171.0,"(POLYGON ((-97.838280724409 30.539888366136, -...",3896851.0,8,19,2423.0,335957.0,814.766082,3.579933e+05,3.154563e+05,141.599298,1998.0,78613,13,7.571279,454.0

In [188]:
len(newDF)

53

In [189]:
newDF.to_file('../data/EPIC_data.geojson', driver="GeoJSON")